### ISSUE TITLE
Add Code of conduct

### ISSUE THREAD

**Issue by go-bears** [lektor/lektor-website#105]
Open source projects often include a code of conduct got the project's community. Providing one for lektor cms can make the project more approachable to new contributors.  See http://pybee.org/community/behavior/code-of-conduct/ or 

 http://railsgirlssummerofcode.org/about/code-of-conduct/

I'd be happy to add the CoC! 😃

**Comment by mitsuhiko** [comment]
With pallets (which is where Flask and co. belong to) we settled on this: https://www.palletsprojects.com/governance/rules-of-engagement/

I would be happy to see this here as well but I feel my general opinion towards a lengthy code of conduct is quite ambivalent.

**Comment by go-bears** [comment]
I think re-purposing Pallets's code of conduct sounds great. Would you like us to add a separate page and post the link to the Community page? or would it be appropriate to add the code of conduct text to the page that already exists?

**Comment by go-bears** [comment]
thanks link and advice @mitsuhiko! we updated the community page with the rules of engagement from Pallets project.

**Comment by hackebrot** [comment]
Since #115 has been merged, I think this issue can be closed! 👏
