### ISSUE TITLE
Add section for themes

### ISSUE THREAD

**Issue by joyhchen** [lektor/lektor-website#117]
I'm not sure if we should add a section for themes in the showcase or elsewhere though.

**Comment by tariquesani** [comment]
This version of Lektor does not really support themes. Can you elaborate what you are referring to?

**Comment by joyhchen** [comment]
Lektor sites built as starters like https://github.com/singingwolfboy/lektor-bs4-example

**Comment by tariquesani** [comment]
Ah! yes, I remember reading somewhere that there are plans to have more starter examples. Would be good to have a section of those resources somewhere.

**Comment by nixjdm** [comment]
Though it's not an exact match of https://github.com/singingwolfboy/lektor-bs4-example, between the showcase giving examples and the new, actual theming of Lektor (which does have it's own doc page), I think this is basically covered now.
