### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by rixx** [lektor/lektor-website#147]
While the PR providing Python 3 support has been merged in lektor, the [docs](https://github.com/lektor/lektor-website/blob/master/content/docs/installation/contents.lr) still say that Python 2 is required … is this due to the current large release gap, or just an oversight?

**Comment by singingwolfboy** [comment]
We actually have #100 all ready to go, the problem is https://github.com/lektor/lektor/issues/349. Making a new release means updating all the documentation and building a new Mac app, and we're a little stalled on how to do those things. ☹️

**Comment by rixx** [comment]
Hm. I see (and will of course close this issue, didn't see the PR because I was looking at issues only).

Since I'm just getting started with lektor (migrating from pelican if things work out), I'll probably start with the dev version - is there any way I could use this process to help your with the release process?
