### ISSUE TITLE
Installer doesn't work on Windows

### ISSUE THREAD

**Issue by jschwarzwalder** [lektor/lektor-website#151]
When trying to install on a Windows Machine using both 2.7 and 3.6 I cannot get lektor to install and run a server. 

I get a message about unicode errors.

**Comment by nixjdm** [comment]
I think this was fixed when we released Lektor 3 (for 2.7 and 3.5 - 3.6 is not officially supported yet, YMMV. If you try again and still get an error, please post another issue with the error text.

**Comment by sunk818** [comment]
Windows 10 has Ubuntu 16.0.4 subsystem (WSL) now:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

Makes install Lektor on Windows much easier this way. 

I think documentation can be updated to say Linux, Mac, or Windows using WSL. As long it installs okay and you can run it as server, you can bring up in your browser to start creating your web site.
