### ISSUE TITLE
Lektor 3 vs 2 differences and compatibility?

### ISSUE THREAD

**Issue by mkjsix** [lektor/lektor-website#159]
Hi all,
Are there any release notes or document pointing out the differences between Lektor 2 vs 3? We'd like to move a large web site from v. 2 to 3 but it's not clear what are the differences and if there are major changes we need to handle manually. Is it a transparent operation, so we can just rebuild the site with V3 and expect everything to work (plugins included)? Thank you.

**Comment by nixjdm** [comment]
There are not a lot of visible changes between 2.3 and 3.0.1. See https://github.com/lektor/lektor/blob/master/CHANGES Mainly we began support for Python 3. There should be some new features in 3.1 when it comes out, as well as bugfixes, but all of this should be transparent. We did not break backwards compatibility with 3.0 and won't on any minor version change.
