### ISSUE TITLE
Document more plugin events

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#163]
There are several available markdown related events not listed on https://www.getlektor.com/docs/api/plugins/events/ that should be documented.

- markdown-config
- markdown-meta-init
- markdown-meta-postprocess

And in not yet released master, markdown-lexer-config

**Comment by rlaverde** [comment]
Looking to the comments of the doc page, @mitsuhiko says that the markdown engine is terrible and because of that It isn't documented https://www.getlektor.com/docs/api/plugins/events/#comment-2534271280

What should be improved? or the markdown engine is better now and It's ok to document it?

**Comment by nixjdm** [comment]
Ah, I didn't see that. I simply noticed that the markdown events weren't listed. We could mark them as unstable, but still include some docs for them as they are now, while noting that they are subject to change (though realistically I don't think it be terribly soon at this point). [I'm not aware of any issues to drastically change the markdown event hooks](https://github.com/lektor/lektor/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20markdown), but if we mark it as unstable, we can just update the docs again if / when we do rewrite it.

@mitsuhiko What do you think? Do you have anything in mind to replace the markdown engine with, or some specific problems you could make an issue about, or is one already made I haven't found?

**Comment by rlaverde** [comment]
Maybe @mitsuhiko is refering to this https://github.com/lektor/lektor/blob/master/lektor/markdown.py#L71-L73

"These markdown parsers are all terrible.  Not one of them does not modify internal state."

>I'm not aware of any issues to drastically change the markdown event hooks

Yes, even a rewrite of the markdown logic could preserve the signals logic, maybe the problems will be if plugins assume other things (like the structure of the renderer).

**Comment by nixjdm** [comment]
We're going to go ahead and add these event hooks to the docs, and just mark that they may break in the future if we swap out mistune or really change how we're using it..
