### ISSUE TITLE
Individual Pages for plugins

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#183]
Related to #182 

We could change the layout of the Plugins List to link to individual getlektor.com pages for each Plugin. People could then read more about a plugin right on getlektor.com. To be clear I still want links to the repos. Some of the current descriptions on getlektor are a bit lacking. We could also add the [tags](https://github.com/ajdavis/lektor-tags) plugin to getlektor.com and allow tagging of plugins so that they're easier to discover.

If they all get their own page, they need some content. So then what would the content be? We could simply have a Markdown field and encourage / make better descriptions, or we could use a little JS to grab a project's pre-rendered README (or other file).

@lektor/developers thoughts?

**Comment by goanpeca** [comment]
Sounds good. We could grab the info from PyPi index (the short description) and add information on the status (official, unofficial, last updated (with JS))
