### ISSUE TITLE
link back to the tag page for plugin events from their respective docs page

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#195]
Post #194, The tag page for an event links to the docs, but not vise versa. We should add this in. There's a small enough number of events this could be done manually, but an automated way would be nice.

**Comment by nixjdm** [comment]
See in this ![image](https://user-images.githubusercontent.com/3431410/39724790-56de4aee-520f-11e8-9fcf-eb21bdbd78a2.png), the page recognizes that the tag matches a plugin event, and then offers several links back to the docs, including one to that specific event? I did not modify the actual event doc pages though, so for instance, [this event page](https://www.getlektor.com/docs/api/plugins/events/setup-env/) won't link back to the tag page for `setup-env`. That's what I want to add.

**Comment by goanpeca** [comment]
Ahh ok now I get it. But this is not really a "missing functionality" on the tags plugin, right? just something extra that needs to be done
