### ISSUE TITLE
Add page for all plugin tags

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#197]
With #194 there is a page per plugin tag, but not a page that lists all tags, which I really want. I could not find an easy way of doing this with lektor-tags. Perhaps the easiest way is to update that plugin. It would be really nice to see a list of all tags and have them all be hyperlinked.

**Comment by goanpeca** [comment]
Is this issue being tracjed on lektor-tags repo ?

**Comment by nixjdm** [comment]
Not yet.

**Comment by nixjdm** [comment]
This was possible all along, but I just didn't see it.
