### ISSUE TITLE
plugin team and plugin listing updates

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#203]
@Vesuvium, @odeckmyn, @BarnabyShearer, @pietroalbini, @kwellman, @fschulze, @ajdavis, @spenczar, @humrochagf, @marksteve, @bancek, @sterin, @skorokithakis, @mesbahamin, @gagoman, @Andrew-Shay

Thank you for making your plugins! I want to tell you all that I invited you to the plugin-developers team for the Lektor organization. My intention is to offer that as a place where people who have made plugins can hear of any important news related to plugins. I'll offer an invite to future plugin devs as well.

This comes because of a significant change coming to getlektor.com regarding plugins, that I plan on pulling early next week #194. In short, I request that you check your `setup.py` and update it to include at least a `url` to your plugin's GitHub page and a `long_description` that PyPI understands (getlektor will too). So you're aware, I plan on making the website build at least nightly going forward, so any changes you make in the future will take effect overnight at the latest. Other `setup.py` keys you might want to set can be seen [here](https://github.com/lektor/lektor-website/pull/194/files#diff-2168c94f8db58659442e5da3454a8d7aR85). I will go and update my own and the official plugins.

I also suggest you check my work regarding your plugin(s) specifically, and file an issue or pull request to fix anything. I made tags for your plugins, that you can add or subtract from, for instance.

I will close this issue when #194 is pulled.

Thank you for your work! I appreciate your contributions!

**Comment by humrochagf** [comment]
@nixjdm thank you for the invite, i made the updates as requested, looking forward for these changes

**Comment by nixjdm** [comment]
@skorokithakis We will be pulling data from PyPI, so small version bump and upload to PyPI is necessary for any changes in setup.py to change what getlektor.com will display (and PyPI, of course).

**Comment by skorokithakis** [comment]
@nixjdm Ah, thanks. I've released the updated descriptions (took three or four tries each, but we're good now), thank you!

**Comment by ajdavis** [comment]
I'm not using Lektor nor maintaining my plugins. (It didn't scale for my site, for reasons I'm happy to discuss some time if you're curious.) @nixjdm would you like me to transfer ownership of my plugins to you?

**Comment by nixjdm** [comment]
@ajdavis Sure. I've even been thinking of extending lektor-tags in particular and (assuming you were cool with it) making it official. Could you please give me permissions on pypi.org as well, so I can update the projects on that site too? Thanks for letting me keep them alive! You made some good ones.

I am aware some scaling issues, and it's near the top of my priority list to dig into and hopefully fix. If you already have to some degree, I'm all ears. Perhaps https://github.com/lektor/lektor/issues/180 or https://github.com/lektor/lektor/issues/498 fit what you've found?

**Comment by ajdavis** [comment]
Yes I think https://github.com/lektor/lektor/issues/180 describes what I was suffering from. I have 400 blog posts that each link to the next/previous post. That means changing one post causes a cache-invalidation cascade the rebuilds the whole site. Armin's parting comment on that ticket seems right: track dependencies in finer detail.

I've transferred GitHub ownership to you for my plugins and added you as co-owner for them on PyPI, I hereby relinquish them and give you permission to do what you like. Let me know if I missed anything, and enjoy.

**Comment by nixjdm** [comment]
Thank you @ajdavis.

**Comment by nixjdm** [comment]
Alright everyone, it's pushed! https://www.getlektor.com/plugins/

You may want to check the category I put your plugin in, and its tags. If you want to modify any of it, just let me know. Gitter, issue here, or pull request is fine. Thanks!
