### ISSUE TITLE
plugin menue changes

### ISSUE THREAD

**Issue by arunpersaud** [lektor/lektor-website#214]
on the web page, if I click on Plugins I see 'List' as the first submenu. This disappears once I click on Plugins->Publishing for example. Not sure if this is a bug in lektor or in the setup.... but I thought I report it here.

**Comment by nixjdm** [comment]
Can you tell me what url you were on when you saw this? Was it when you were running the site locally or on the production getlektor.com? A screenshot might help too. I haven't seen this.

If you've been to the prod site before a week ago, you could find "List" in the tree menu on the left in https://www.getlektor.com/docs/plugins/, pointing to https://www.getlektor.com/docs/plugins/list/, but that has been removed. You shouldn't be able to see it anymore. If you can, perhaps clear your cache? The page still exists as a redirect to https://www.getlektor.com/plugins/

**Comment by arunpersaud** [comment]
this was on the production site, but most likely do to an old cache on my side. Clearing the cache removed the 'list' entry from the menu and now it doesn't show up anymore... sorry for the noise.

**Comment by nixjdm** [comment]
No problem! I'd rather have this than a bug go unreported!
