### ISSUE TITLE
Update to webpack 4

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#219]
See https://github.com/lektor/lektor-webpack-support/issues/20

We ought to be able to build with modern webpack, and then we can update that issue too.

**Comment by xlotlu** [comment]
This has been handled in https://github.com/lektor/lektor/commit/b5e320a7024867e531edf2ec0f96f75fa73df896

**Comment by runfalk** [comment]
This is actually not fixed yet: https://github.com/lektor/lektor-website/blob/master/webpack/package.json#L25

The link you're poiting to is for the admin (which is updated). I assume this issue is for the website.

**Comment by xlotlu** [comment]
> This is actually not fixed yet:
> https://github.com/lektor/lektor-website/blob/master/webpack/package.json#L25

Oops

**Comment by xlotlu** [comment]
@lektor/developers could someone make an effort on this? It would be nice to have this cleared before splitting the docs away.

**Comment by yagebu** [comment]
Fixed in #328
