### ISSUE TITLE
installation instructions suggest using sudo

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor-website#267]
Quoting the *nix installation instructions:

> If you are not logged in as superuser, instead you should try this:
> ```
> $ curl -sf https://www.getlektor.com/install.sh | sudo sh
> ```

That is just... bad. Asking people to run random stuff from the internet as root is bad. It's also probably unnecessary after a quick look at the code.

**Comment by runfalk** [comment]
Not that I disagree, but for most users `curl url | sh` is just as bad/insecure. While you may not be able to instantly compromise the entire system all user data is still at risk. That's just the nature of running untrusted code.

The problem I see with removing the `sudo` requirement is that we basically have to put the binary in `~/.local/bin` which may not be part of the user's `PATH`. This would make the installation less robust.

Maybe we could copy how [rustup](https://rustup.rs/) does it (asking if it should modify the `PATH`)?

**Comment by xlotlu** [comment]
> Maybe we could copy how [rustup](https://rustup.rs/) does it (asking if it should modify the `PATH`)?

A tentative +1, but that's a lot of boilerplate. Thing is, I already have `~/.local/bin/` in my `$PATH` (and I have no idea who added it there, must've been a debian config change at some point).

And thing two is that... https://github.com/lektor/lektor-website/blob/9449a161ec185f5dc34d65541d8a15afaad7b750/assets/install.sh#L140

Note the code for `find_user_paths()` and `find_locations()` -- the user is already prompted to fix it on their own.
