### ISSUE TITLE
BUG: Installing on windows fails. --prefer-binary option for the venv pip is not recognized.

### ISSUE THREAD

**Issue by JVanloofsvelt** [lektor/lektor-website#306]
On Windows, the virtual environment created by installer.py comes with an old pip version. It complains about the option '--prefer-binary' since this option was not supported by the old pip version.

It might be related to the fact that I have an older Python 3.5 installation that came with an older pip version.

**Comment by JVanloofsvelt** [comment]
I did some research, apparently the installer has three strategies for creating a virtualenv: 

1. using the builtin venv module
2. using virtualennv from site-packages if venv was not an option
3. Downloading virtual env if virtualenv was not an option

Remarks:
- The built-in 'venv' module uses the builtin 'ensurepip' module, which comes bundled with a pip version. This version cannot be updated, it is supposed to be frozen with the specific Python distribution/version.
- The '--prefer-binary' option for pip was added in pip version 18.0

How should the installer.py be modified then? 
IMO: use_venv() should fail (or rather be skipped) if the pip version that comes with ensurepip() is older than version 18.0.

**Comment by JVanloofsvelt** [comment]
I'm guessing I created this issue in the wrong repository. I created a copy in the Lektor repository: https://github.com/lektor/lektor/issues/808

**Comment by andresperezcera** [comment]
Not the wrong repo if the fix can be applied to the installer script located [here](https://github.com/lektor/lektor-website/blob/master/assets/installer.py).

**Comment by JVanloofsvelt** [comment]
Thanks Andres, I was looking for it!

**Comment by CAM-Gerlach** [comment]
This can be closed along with #307 , presumably, since it sounds like the old installer script will be deprecated/removed if it isn't already.
