### ISSUE TITLE
The Travis CI build failed for Lektor website

### ISSUE THREAD

**Issue by jurgenizer** [lektor/lektor-website#314]
New content added to content section of forked Lektor site. PR caused build to fail x 2. Please help when you get a chance.
![error](https://user-images.githubusercontent.com/8074200/105006733-b7525d80-5a3f-11eb-94a5-6c831f9682c1.png)
![log](https://user-images.githubusercontent.com/8074200/105006750-bb7e7b00-5a3f-11eb-8685-47d4f7996a6b.png)

**Comment by dairiki** [comment]
I believe we've ignored this long enough that it should no longer be an issue.  (We no longer use Travis, and the werkzeug version conflict has been fixed in lektor >= 3.2.3.)

Closing.  Feel free to re-open if necessary.
