### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by danger89** [lektor/lektor-website#329]
When using the installer.py script from the website. I get an error in Python.

```sh
$ curl -sf https://www.getlektor.com/installer.py | python3
...
...
Building wheels for collected packages: inifile
  Building wheel for inifile (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/melroy/.local/lib/lektor/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l6wsyh8h/inifile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l6wsyh8h/inifile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5gr62lli
       cwd: /tmp/pip-install-l6wsyh8h/inifile/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for inifile
```

I already tried running `pip install wheel` or `pip3 install wheel`, but it said that package was already installed. It didn't help.

What now?

Regards,
Melroy van den Berg

**Comment by dairiki** [comment]
> Maybe this installer is broken..

Yes, the installer script is pretty much dead.  The recommended installation method is now `pipx`.
See also #325 and lektor/lektor#915.

Sorry for the confusion.  I _think_ the reason that the online documentation is stale now is that none of the active devs have credentials to publish to [getlektor.com](https://getlektor.com).  (See comments towards the bottom of [lektor/lektor#724](https://github.com/lektor/lektor/issues/724#issuecomment-922553756).)

**Comment by danger89** [comment]
I think @mitsuhiko should be able to grant devs access. Or he change the website himself. Either way, please update getlektor website.

**Comment by dairiki** [comment]
As noted, the recommended installation method is now via `pipx` (see #325 and lektor/lektor#915).

The website will be updated as soon as we get back to being able to publish updates to the public site.  (#330, #337)

Closing.
