### ISSUE TITLE
Deployment to public website is broken (invalid credentials in the repo secrets)

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor-website#330]
The [deploy.yml][] workflow attempts to build and deploy the website when commits are made to the master branch.  The building part appears to work, but the [deployment part is failing][fail], apparently due to missing or invalid credentials in the github repository's secrets.

As a result updates to lektor-website are not being propagated to [getlektor.com](https://getlektor.com).  The public site is becoming pretty stale.

Who can fix this? @mitsuhiko?

[deploy.yml]: https://github.com/lektor/lektor-website/blob/254aa8e8b93a4968bf54fb55c04dd40dae11226e/.github/workflows/deploy.yml
[fail]: https://github.com/lektor/lektor-website/runs/3644082241?check_suite_focus=true#step:8:876
[webfactory/ssh-agent]: https://github.com/webfactory/ssh-agent
[rrsync]: https://biplane.com.au/blog/?p=591

**Comment by nixjdm** [comment]
I can see `LEKTOR_DEPLOY_PASSWORD` and `LEKTOR_DEPLOY_USERNAME` in this repo's secrets, updated spring of last year, but I can't see their contents, and I don't have direct access to the server. @mitsuhiko, I think you're the only one here with server access. Can you take a look and maybe fix this?

**Comment by maste9** [comment]
@dairiki I guess that's the answer to [my request from the gitter channel](https://matrix.to/#/!XqpnRYuTcRNpePLAFJ:gitter.im/$RpMxwNMWFrPGFaLD8BlLWNdRKUPJyJz7AfS_ctyGT0E?via=gitter.im&via=matrix.org&via=ismus.net)?

For I still don't see any new plugins on getlektor.com 😞

**Comment by dairiki** [comment]
PR #337 will publish the site to github pages with a CNAME file setting the "custom domain" to `www.getlektor.com`.

**Comment by dairiki** [comment]
> I think the right solution here would be to port all of this to github pages. I can rebind the DNS if someone can publish it there.

@mitsuhiko  I still think we're still ready to switch to GH Pages.  We have a [GitHub action](https://github.com/lektor/lektor-website/blob/master/.github/workflows/deploy.yml) set up that publishes to https://lektor.github.io/lektor-website/

I think all that we need DNS-wise is:
```
www.getlektor.com. CNAME lektor.github.io.
```

And, ideally, the following records at `getlektor.com` (to allow GitHub to do the redirect from getlektor.com to www.getlektor.com):
```
getlektor.com. A 185.199.108.153
getlektor.com. A 185.199.109.153
getlektor.com. A 185.199.110.153
getlektor.com. A 185.199.111.153
getlektor.com. AAAA 2606:50c0:8000::153
getlektor.com. AAAA 2606:50c0:8001::153
getlektor.com. AAAA 2606:50c0:8002::153
getlektor.com. AAAA 2606:50c0:8003::153
```
(or, if the registrar/DNS service supports the non-standard ALIAS or ANAME "records", this can be done more tersely as `getlektor.com. ALIAS lektor.github.io.` — or similar with ANAME)

Once that's done, merge #337 to create the CNAME file.

GitHub's instructions on all of this are [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site).

**Comment by dwt** [comment]
@mitsuhiko Do you have an update when you'll be able to rebind the DNS? I would really like the lektor website move to GitHub pages and that seems to currently block this solid. :/

**Comment by dairiki** [comment]
@mitsuhiko Ping!

> I think the right solution here would be to port all of this to github pages. I can rebind the DNS if someone can publish it there.

We've implemented a workflow that publishes to github pages.  That was done over two months ago.
Please, either make the DNS updates to point getlektor.com to the github pages, or let us know some alternative plan to be able to update the content on the getlektor.com website.

Thank you!

**Comment by nixjdm** [comment]
I don't want to make the burden of doing this any harder, but if you're ok with it @mitsuhiko, I'd suggest modifying the DNS at the same time to support an eventual `docs.` subdomain, as hoped for in #226. If that's done ahead of time, that move could be done by other maintainers when ready, so you wouldn't be needed to step in at that point, too.

@dairiki Is that a simple extension of the snippet you provided above, like I'd think? Is there a reason not to do this? The only negative effect that's obvious to me is `docs.` subdomain resolving while not being used unless/until that work completes. But while getlektor.com/docs still works, that doesn't seem like a big deal to me.

**Comment by dairiki** [comment]
> I'd suggest modifying the DNS at the same time to support an eventual `docs.` subdomain, as hoped for in #226.

This is probably not a good idea unless/until we have a site ready to go for the subdomain.

If DNS for a domain name is pointed to Github pages (and that domain name has not been ["verified"](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages) — i.e. claimed — by a specific user or organization) then _any_ Github pages site may claim to be that domain and serve up arbitrary content.  (More [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#securing-the-custom-domain-for-your-github-pages-site).)

----

Which brings up the point that the `lektor` Github organization ideally should "verify" ownership of the `getlektor.com` domain.  This requires creating a special TXT record in DNS for the domain, (and also requires Github permissions to edit organization settings which I, apparently, do not have.)
@mitsuhiko, If you feel like attempting this, instructions are [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-organization-site).

**Comment by nixjdm** [comment]
I see, thanks. Could we instead post a trivial page then in order to verify it, like an html redirect to `/docs/`? Then that could one day be updated. I'm just trying to get the most out of a single session of @mitsuhiko's time here.

Also I'm pretty sure I do have sufficient GitHub org perms to modify those settings, so I can try to help there. I just don't have DNS access.

**Comment by dairiki** [comment]
My understanding is that if we "verify" the `getlektor.com` domain (by going through the process involving creating a custom TXT record) that would protect all immediate subdomains (e.g. `docs.getlektor.com`) from being claimed by any Github pages sites outside of the lektor organization.
So, if that is done, there is no real need to create a stub site to project the domain — not that that's a bad idea.  (If DNS is pointed to Github pages and no site claims that domain, Github serves up a 404 page: "There isn't a GitHub Pages site here.")

**Comment by dairiki** [comment]
> Also I'm pretty sure I do have sufficient GitHub org perms to modify those settings, so I can try to help there. I just don't have DNS access.

@nixjdm If you can, it is probably a good idea to go through the steps to verify ownership of `getlektor.com` (instructions [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-organization-site)) up to to step that requires DNS access.  Then pass on the details of the TXT record to be created to @mitsuhiko.  Finally, when the TXT record has been created (even if that takes a while) it sounds like you can click the button to complete the process.

**Comment by nixjdm** [comment]
The txt record is ready to be added. I can verify it after it is added and has propagated. @mitsuhiko could you please then, in addition to @dairiki's [previous instructions](https://github.com/lektor/lektor-website/issues/330#issuecomment-1068613165), also add the txt record listed [here](https://github.com/organizations/lektor/settings/pages_verified_domains/getlektor.com)?

**Comment by dairiki** [comment]
(@nixjdm The link to the txt record you provided 404s for me.  Hopefully, it works for organization admins.)

**Comment by nixjdm** [comment]
Yes, it should for Armin.

**Comment by dairiki** [comment]
@mitsuhiko  Here's a quarterly ping to keep this thread alive.

If you could point DNS for {www.,}getlektor.com to our GH Pages, that would allow us to be able to update the website.

If, for whatever reason, you're unwilling or unable to do so, let us know, too, so we can stop holding or breath ;-) 

Thank you!

**Comment by dwt** [comment]
@dairiki Not sure he's actually getting the emails from here, have you tried emailing him directly or giving him a call?

**Comment by dairiki** [comment]
@dwt Email sent (just now)

**Comment by mitsuhiko** [comment]
I rebound the addresses to point to github pages instead. Should go into effect soon.
