### ISSUE TITLE
Get plugin pages to update more regularly

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor-website#331]
The lower hanging fruit here is to re-enable nightly deploys. The old Travis-CI deploys occurred not just on master pushes, but also nightly, which would yield a fresh render of pages like this https://www.getlektor.com/plugins/lektor-atom/, which currently is out-of-date by ~3 months.

Alternatively, someone could replace the [python for this](https://github.com/lektor/lektor-website/tree/master/packages/project-data) with JS to pull that data on-the-fly.

**Comment by dairiki** [comment]
I've just pushed 2de648952ebf31a17dc902c5d5f81ac86b5b268e to master which adds a [schedule][] to [deploy.yml][] that should cause the workflow to run every night. (We'll see tomorrow...)  It also enables running the workflow via [workflow_dispatch][], which allows it to be run manually from the _[Actions][]_ page.

The problem remains (as noted in #330) that the project secrets, as being used by the workflow, appear to be either missing or incorrect. The rsync deployment to `flow.srv.pocoo.org` is failing with "permission denied".  (See the workflow log, [here][1].)

(I don't have sufficient privileges to manage the repo secrets.  They might not even exist, as far as I can tell.)

[actions]: https://github.com/lektor/lektor-website/actions/workflows/deploy.yml
[schedule]: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule
[workflow_dispatch]: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#manual-events
[deploy.yml]: https://github.com/lektor/lektor-website/blob/2de648952ebf31a17dc902c5d5f81ac86b5b268e/.github/workflows/deploy.yml
[1]: https://github.com/lektor/lektor-website/runs/4591847240?check_suite_focus=true#step:9:863

**Comment by dairiki** [comment]
The scheduled run of `deploy.yml` [appears to have run](https://github.com/lektor/lektor-website/actions/runs/1609610348).
(It didn't update the website due to the same "permission denied" issue mentioned above.)

Closing this issue in favor of #330.
