### ISSUE TITLE
WigleWifi log report

### ISSUE THREAD

**Issue by xxxfxxxfxxx** [lektor/lektor-website#390]
Log Data:

03:36:53.046 GuardThread-Thread-4] Service is foreground: true
03:36:58.611 main] MAIN: pause.
03:36:58.611 main] Pause; setting allowRefresh
03:36:59.050 main] MAIN: stop.
03:36:59.051 main] MAIN: onSaveInstanceState
03:37:08.054 GuardThread-Thread-4] Service is foreground: true
03:37:20.305 main] MAIN: restart.
03:37:20.306 main] MAIN: start.
03:37:20.307 main] MAIN: resume.
03:37:20.308 main] GoogleApiAvailability: 0
03:37:20.309 main] MAIN: post resume.
03:37:20.309 main] resume settings.
03:37:20.309 main] Resume with allow: true
03:37:20.312 main] current selection: ALL: (3)
03:37:20.385 main] current lang: ar new lang: 
03:37:20.386 main] showMyDiscovered setting map data: ALL
03:37:20.386 pool-1520-thread-1] set theme called: 2
03:37:23.064 GuardThread-Thread-4] Service is foreground: true
03:37:29.770 main] MAIN: pause.
03:37:29.770 main] Pause; setting allowRefresh
03:37:29.781 main] current lang: ar new lang: 
03:37:30.287 main] MAIN: stop.
03:37:30.288 main] MAIN: onSaveInstanceState
03:37:38.075 GuardThread-Thread-4] Service is foreground: true
03:37:41.274 main] speak: نفذ 27, New WiFi 1, New cell 3, بلوتوث جديد 39, from 3.9 أمتار, 3 37 AM, battery 73 percent,

**Comment by dairiki** [comment]
This appears to be spew unrelated to Lektor.  Closing.
