### ISSUE TITLE
The URL for the repository is probably wrong

### ISSUE THREAD

**Issue by davidbgk** [lektor/lektor-website#4]
![capture d ecran 2015-12-21 a 17 20 25](https://cloud.githubusercontent.com/assets/3556/11935263/2fe41720-a807-11e5-9b8c-3934f04f66c1.png)

s/getsentry/lektor/

**Comment by jeffwidman** [comment]
Looks like this has been fixed

**Comment by niijv** [comment]
Yes, thank you. I will close this.
